# Generated by Django 3.1.3 on 2020-12-13 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_file_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='version',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
