# Generated by Django 3.1.3 on 2020-12-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_file_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
